services:
  # app:
  #   build:
  #     context: .
  #     target: final
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - '.env.development.local'
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

  db:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - '.env.development.local'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
