services:
  db:
    image: postgres:alpine
    container_name: postgres-inventory
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
